UPDATE Beliefs SET MinPopulation = '0' WHERE Type = 'BELIEF_GODDESS_LOVE';

INSERT INTO Belief_ResourceYieldChanges (BeliefType,ResourceType,YieldType,Yield)
SELECT 'BELIEF_OPEN_SKY','RESOURCE_COW','YIELD_SCIENCE',1 UNION ALL
SELECT 'BELIEF_OPEN_SKY','RESOURCE_SHEEP','YIELD_SCIENCE',1 UNION ALL
SELECT 'BELIEF_OPEN_SKY','RESOURCE_HORSE','YIELD_SCIENCE',1;

Delete FROM Belief_ResourceYieldChanges WHERE BeliefType = 'BELIEF_EARTH_MOTHER';
INSERT INTO Belief_ResourceYieldChanges (BeliefType,ResourceType,YieldType,Yield)
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_SPICES','YIELD_FOOD',1 UNION ALL
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_BANANA','YIELD_FOOD',1 UNION ALL
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_COTTON','YIELD_FOOD',1 UNION ALL
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_CITRUS','YIELD_FOOD',1 UNION ALL
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_SPICES','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_BANANA','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_COTTON','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_EARTH_MOTHER','RESOURCE_CITRUS','YIELD_FAITH',1 ;

UPDATE Beliefs SET CityGrowthModifier = '0' WHERE Type = 'BELIEF_FERTILITY_RITES';
INSERT INTO Belief_BuildingClassYieldChanges(BeliefType,BuildingClassType,YieldType,YieldChange)
SELECT 'BELIEF_FERTILITY_RITES','BUILDINGCLASS_GRANARY','YIELD_FAITH',2;
INSERT INTO Belief_ResourceYieldChanges (BeliefType,ResourceType,YieldType,Yield)
SELECT 'BELIEF_FERTILITY_RITES','RESOURCE_WHEAT','YIELD_FAITH',1;

UPDATE Beliefs SET MinPopulation = '0' WHERE Type = 'BELIEF_GOD_CRAFTSMEN';
DELETE FROM Belief_CityYieldChanges WHERE BeliefType = 'BELIEF_GOD_CRAFTSMEN';
INSERT INTO Belief_ResourceYieldChanges (BeliefType,ResourceType,YieldType,Yield)
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_JADE','YIELD_PRODUCTION',1 UNION ALL
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_AMBER','YIELD_PRODUCTION',1 UNION ALL
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_CORAL','YIELD_PRODUCTION',1 UNION ALL
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_LAPIS','YIELD_PRODUCTION',1 UNION ALL
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_JADE','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_AMBER','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_CORAL','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_GOD_CRAFTSMEN','RESOURCE_LAPIS','YIELD_FAITH',1;

DELETE FROM Belief_TerrainYieldChanges WHERE BeliefType = 'BELIEF_DANCE_AURORA';
INSERT INTO Belief_CityYieldChanges (BeliefType,YieldType,Yield)
SELECT 'BELIEF_DANCE_AURORA','YIELD_PRODUCTION',2;

UPDATE Beliefs SET WonderProductionModifier = '10',ObsoleteEra = 'ERA_INDUSTRIAL' WHERE Type = 'BELIEF_ANCESTOR_WORSHIP';
DELETE FROM Belief_BuildingClassYieldChanges WHERE BeliefType = 'BELIEF_ANCESTOR_WORSHIP';
INSERT INTO Belief_BuildingClassYieldChanges(BeliefType,BuildingClassType,YieldType,YieldChange)
SELECT 'BELIEF_ANCESTOR_WORSHIP','BUILDINGCLASS_SHRINE','YIELD_CULTURE',1 UNION ALL
SELECT 'BELIEF_ANCESTOR_WORSHIP','BUILDINGCLASS_SHRINE','YIELD_FAITH',1;

UPDATE Beliefs SET CityRangeStrikeModifier = '0' WHERE Type='BELIEF_GODDESS_STRATEGY';
INSERT INTO Belief_BuildingClassYieldChanges(BeliefType,BuildingClassType,YieldType,YieldChange)
SELECT 'BELIEF_GODDESS_STRATEGY','BUILDINGCLASS_CASTLE','YIELD_CULTURE',4 UNION ALL
SELECT 'BELIEF_GODDESS_STRATEGY','BUILDINGCLASS_WALLS','YIELD_FAITH',2;

INSERT INTO Belief_FeatureYieldChanges (BeliefType,FeatureType,YieldType,Yield)
SELECT 'BELIEF_DESERT_FOLKLORE','FEATURE_OASIS','YIELD_CULTURE',2 UNION ALL
SELECT 'BELIEF_DESERT_FOLKLORE','FEATURE_OASIS','YIELD_FAITH',1 ;

Delete FROM Belief_BuildingClassYieldChanges WHERE BeliefType = 'BELIEF_GOD_KING';
INSERT INTO Belief_BuildingClassYieldChanges(BeliefType,BuildingClassType,YieldType,YieldChange)
SELECT 'BELIEF_GOD_KING','BUILDINGCLASS_PALACE','YIELD_FAITH',3 UNION ALL
SELECT 'BELIEF_GOD_KING','BUILDINGCLASS_CITY_HALL_LV1','YIELD_PRODUCTION',1 UNION ALL
SELECT 'BELIEF_GOD_KING','BUILDINGCLASS_CITY_HALL_LV1','YIELD_CULTURE',1 UNION ALL
SELECT 'BELIEF_GOD_KING','BUILDINGCLASS_CITY_HALL_LV1','YIELD_FOOD',1 ;

INSERT INTO Belief_ImprovementYieldChanges (BeliefType,ImprovementType,YieldType,Yield)
SELECT 'BELIEF_GODDESS_HUNT','IMPROVEMENT_CAMP','YIELD_FAITH',1 ;
INSERT INTO Belief_ResourceYieldChanges (BeliefType,ResourceType,YieldType,Yield)
SELECT 'BELIEF_GODDESS_HUNT','RESOURCE_DEER','YIELD_PRODUCTION',1 UNION ALL
SELECT 'BELIEF_GODDESS_HUNT','RESOURCE_BISON','YIELD_FOOD',1 ;

INSERT INTO Belief_FeatureYieldChanges (BeliefType,FeatureType,YieldType,Yield)
SELECT 'BELIEF_SACRED_PATH','FEATURE_JUNGLE','YIELD_FAITH',1;

Delete FROM Belief_ImprovementYieldChanges WHERE BeliefType = 'BELIEF_GOD_SEA';
INSERT INTO Belief_ImprovementYieldChanges (BeliefType,ImprovementType,YieldType,Yield)
SELECT 'BELIEF_GOD_SEA','IMPROVEMENT_FISHFARM_MOD','YIELD_CULTURE',1 UNION ALL
SELECT 'BELIEF_GOD_SEA','IMPROVEMENT_FISHERY_MOD','YIELD_CULTURE',1 UNION ALL
SELECT 'BELIEF_GOD_SEA','IMPROVEMENT_FISHING_BOATS','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_GOD_SEA','IMPROVEMENT_FISHING_BOATS','YIELD_CULTURE',1;

INSERT INTO Belief_ImprovementYieldChanges (BeliefType,ImprovementType,YieldType,Yield)
SELECT 'BELIEF_ORAL_TRADITION','IMPROVEMENT_PLANTATION','YIELD_GOLD',1;
INSERT INTO Belief_ResourceYieldChanges (BeliefType,ResourceType,YieldType,Yield)
SELECT 'BELIEF_ORAL_TRADITION','RESOURCE_TEA','YIELD_CULTURE',1 UNION ALL
SELECT 'BELIEF_ORAL_TRADITION','RESOURCE_SILK','YIELD_CULTURE',1 ;

DELETE FROM Belief_ResourceYieldChanges WHERE BeliefType = 'BELIEF_SUN_GOD';
INSERT INTO Belief_ResourceYieldChanges (BeliefType,ResourceType,YieldType,Yield)
SELECT 'BELIEF_SUN_GOD','RESOURCE_OLIVE','YIELD_SCIENCE',1 UNION ALL
SELECT 'BELIEF_SUN_GOD','RESOURCE_TOBACCO','YIELD_SCIENCE',1 UNION ALL
SELECT 'BELIEF_SUN_GOD','RESOURCE_PERFUME','YIELD_SCIENCE',1 UNION ALL
SELECT 'BELIEF_SUN_GOD','RESOURCE_SUGAR','YIELD_SCIENCE',1 UNION ALL
SELECT 'BELIEF_SUN_GOD','RESOURCE_OLIVE','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_SUN_GOD','RESOURCE_TOBACCO','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_SUN_GOD','RESOURCE_PERFUME','YIELD_FAITH',1 UNION ALL
SELECT 'BELIEF_SUN_GOD','RESOURCE_SUGAR','YIELD_FAITH',1 ;

INSERT INTO Belief_BuildingClassYieldChanges(BeliefType,BuildingClassType,YieldType,YieldChange)
SELECT 'BELIEF_GOD_WAR','BUILDINGCLASS_BARRACKS','YIELD_FAITH',2 UNION ALL
SELECT 'BELIEF_GOD_WAR','BUILDINGCLASS_ARMORY','YIELD_FAITH',2;

DELETE FROM Belief_YieldChangeTradeRoute WHERE BeliefType = 'BELIEF_MESSENGER_GODS';
INSERT INTO Belief_YieldChangeTradeRoute (BeliefType,YieldType,Yield)
SELECT 'BELIEF_MESSENGER_GODS','YIELD_FAITH',2 UNION ALL
SELECT 'BELIEF_MESSENGER_GODS','YIELD_SCIENCE' ,2;

UPDATE Beliefs SET PlotCultureCostModifier = '-50' WHERE Type = 'BELIEF_RELIGIOUS_SETTLEMENTS';
INSERT INTO Belief_CityYieldChanges (BeliefType,YieldType,Yield)
SELECT 'BELIEF_RELIGIOUS_SETTLEMENTS','YIELD_CULTURE',2 ;

INSERT INTO Belief_FeatureYieldChanges (BeliefType,FeatureType,YieldType,Yield)
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_FOUNTAIN_YOUTH','YIELD_FOOD',4 UNION ALL
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_FOUNTAIN_YOUTH','YIELD_FAITH',4 UNION ALL
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_FOUNTAIN_YOUTH','YIELD_PRODUCTION',2 UNION ALL
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_FOUNTAIN_YOUTH','YIELD_SCIENCE',2 UNION ALL
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_LAKE_VICTORIA','YIELD_CULTURE',4 UNION ALL
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_LAKE_VICTORIA','YIELD_FAITH',4 UNION ALL
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_LAKE_VICTORIA','YIELD_PRODUCTION',2 UNION ALL
SELECT 'BELIEF_GODDESS_OF_PURITY','FEATURE_LAKE_VICTORIA','YIELD_SCIENCE',2;

INSERT INTO Belief_TerrainYieldChanges (BeliefType,TerrainType,YieldType,Yield)
SELECT 'BELIEF_SACRED_WATERS','TERRAIN_COAST','YIELD_FAITH',1;

INSERT INTO Belief_TerrainYieldChanges (BeliefType,TerrainType,YieldType,Yield)
SELECT 'BELIEF_SNOW_BELIEF','TERRAIN_TUNDRA','YIELD_FAITH',2 UNION ALL
SELECT 'BELIEF_SNOW_BELIEF','TERRAIN_SNOW','YIELD_FOOD',1 UNION ALL
SELECT 'BELIEF_SNOW_BELIEF','TERRAIN_SNOW','YIELD_FAITH',2;






