--BUILDING_SHOSHONE_HUNTING
INSERT INTO Building_ResourceYieldChanges(BuildingType,ResourceType,YieldType,Yield)
SELECT 'BUILDING_SHOSHONE_HUNTING',ResourceType,'YIELD_PRODUCTION',2
FROM Improvement_ResourceTypes WHERE ImprovementType = 'IMPROVEMENT_PASTURE' OR ImprovementType = 'IMPROVEMENT_CAMP' UNION ALL

SELECT 'BUILDING_SHOSHONE_HUNTING',ResourceType,'YIELD_GOLD',1
FROM Improvement_ResourceTypes WHERE ImprovementType = 'IMPROVEMENT_PASTURE' OR ImprovementType = 'IMPROVEMENT_CAMP' UNION ALL

SELECT 'BUILDING_SHOSHONE_HUNTING',ResourceType,'YIELD_FOOD',1
FROM Improvement_ResourceTypes WHERE ImprovementType = 'IMPROVEMENT_PASTURE' OR ImprovementType = 'IMPROVEMENT_CAMP' ;

--BUILDING_PORTUGAL_PORT
INSERT INTO Building_ResourceYieldChanges(BuildingType,ResourceType,YieldType,Yield)
SELECT 'BUILDING_PORTUGAL_PORT',t1.Type,'YIELD_PRODUCTION',1
FROM Resources t1 LEFT JOIN Resource_TerrainBooleans t2
ON t1.Type = t2.ResourceType
WHERE t1.ResourceClassType = 'RESOURCECLASS_LUXURY' AND t2.TerrainType = 'TERRAIN_COAST' UNION ALL
SELECT 'BUILDING_PORTUGAL_PORT',t1.Type,'YIELD_GOLD',1
FROM Resources t1 LEFT JOIN Resource_TerrainBooleans t2
ON t1.Type = t2.ResourceType
WHERE t1.ResourceClassType = 'RESOURCECLASS_LUXURY' AND t2.TerrainType = 'TERRAIN_COAST' ;

-- BUILDING_CARTHAGINIAN_AGORA Effect
insert into Policies (`Type`, `Description`, Help, PortraitIndex, IconAtlas, IconAtlasAchieved, Dummy) values
('POLICY_BUILDING_CARTHAGINIAN_AGORA_COMMERCE', 'TXT_KEY_BUILDING_CARTHAGINIAN_AGORA_COMMERCE_DESCRIPTION', 'TXT_KEY_BUILDING_CARTHAGINIAN_AGORA_COMMERCE_HELP', 32, 'POLICY_ATLAS', 'POLICY_A_ATLAS', 1),
('POLICY_BUILDING_CARTHAGINIAN_AGORA_EXPLORATION', 'TXT_KEY_BUILDING_CARTHAGINIAN_AGORA_EXPLORATION_DESCRIPTION', 'TXT_KEY_BUILDING_CARTHAGINIAN_AGORA_EXPLORATION_HELP', 32, 'POLICY_ATLAS', 'POLICY_A_ATLAS', 1);

insert into Policy_HurryModifiers (PolicyType, HurryType, HurryCostModifier) values
('POLICY_BUILDING_CARTHAGINIAN_AGORA_COMMERCE', 'HURRY_GOLD', -5);

insert into UnitPromotions (Type, Description, Help, CannotBeChosen, CombatPercent, PortraitIndex, IconAtlas) values
('PROMOTION_CARTHAGINIAN_AGORA_EXPLORATION', 
'TXT_KEY_BUILDING_CARTHAGINIAN_AGORA_EXPLORATION_DESCRIPTION', 
'TXT_KEY_BUILDING_CARTHAGINIAN_AGORA_EXPLORATION_HELP',
1,
10,
54,
'SP_PROMOTION_ATLAS');

insert into UnitPromotions_UnitCombats(PromotionType, UnitCombatType) values
('PROMOTION_CARTHAGINIAN_AGORA_EXPLORATION', 'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_CARTHAGINIAN_AGORA_EXPLORATION', 'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_CARTHAGINIAN_AGORA_EXPLORATION', 'UNITCOMBAT_CARRIER'),
('PROMOTION_CARTHAGINIAN_AGORA_EXPLORATION', 'UNITCOMBAT_SUBMARINE');

insert into Policy_FreePromotions (PolicyType, PromotionType) values
('POLICY_BUILDING_CARTHAGINIAN_AGORA_EXPLORATION', 'PROMOTION_CARTHAGINIAN_AGORA_EXPLORATION');

-- BUILDING_CHINESE_GARDEN Effect
insert into Building_BuildingClassYieldChanges(BuildingType, BuildingClassType, YieldType, YieldChange)
select 'BUILDING_CHINESE_GARDEN', Buildings.BuildingClass, Yields.Type, 1
from Buildings
left join Yields
left join CitySizeBuildings
on Buildings.Type = CitySizeBuildings.BuildingType
where Buildings.Type like 'BUILDING_CITY_SIZE%' and Yields.Type in ('YIELD_FOOD', 'YIELD_SCIENCE', 'YIELD_GOLDEN_AGE_POINTS') and CitySizeBuildings.CitySize >= 4;