--move cultural specialist output to table SpecialistYields
INSERT INTO SpecialistYields(SpecialistType,YieldType,Yield)
SELECT Type , 'YIELD_CULTURE',4 
FROM Specialists WHERE CulturePerTurn > 0;
UPDATE Specialists Set CulturePerTurn = 0;

--GreatPeopleImprovement provide surrounding output
INSERT INTO Improvement_AdjacentImprovementYieldChanges(ImprovementType,OtherImprovementType,YieldType,Yield)
SELECT	'IMPROVEMENT_ACADEMY',Type,  'YIELD_SCIENCE', 1 FROM Improvements UNION ALL
SELECT	'IMPROVEMENT_CUSTOMS_HOUSE',Type,  'YIELD_GOLD', 3 FROM Improvements UNION ALL
SELECT	'IMPROVEMENT_MANUFACTORY',Type,  'YIELD_PRODUCTION', 1 FROM Improvements UNION ALL
SELECT	'IMPROVEMENT_HOLY_SITE',Type,  'YIELD_FAITH', 1 FROM Improvements ;

CREATE TRIGGER SP_AdjacentImprovementYieldChangesForNewImproments
AFTER INSERT ON Improvements
WHEN New.Type != 'IMPROVEMENT_INCA_CITY' AND New.Type NOT LIKE 'IMPROVEMENT_POLYNESIA_CITY_%'
BEGIN
	INSERT INTO Improvement_AdjacentImprovementYieldChanges(ImprovementType,OtherImprovementType,YieldType,Yield)
    SELECT 'IMPROVEMENT_ACADEMY',       New.Type, 'YIELD_SCIENCE',      1 UNION ALL
    SELECT 'IMPROVEMENT_CUSTOMS_HOUSE', New.Type, 'YIELD_GOLD',         3 UNION ALL
    SELECT 'IMPROVEMENT_MANUFACTORY',   New.Type, 'YIELD_PRODUCTION',   1 UNION ALL
    SELECT 'IMPROVEMENT_HOLY_SITE',     New.Type, 'YIELD_FAITH',        1 ;
END;

UPDATE Improvements SET WonderProductionModifier = 10 WHERE Type = 'IMPROVEMENT_MANUFACTORY';
UPDATE Improvements SET ImprovementResource = 'RESOURCE_MANPOWER', ImprovementResourceQuantity = 10 WHERE Type = 'IMPROVEMENT_MANUFACTORY';
UPDATE Improvements SET ImprovementResource = 'RESOURCE_CONSUMER', ImprovementResourceQuantity = 20 WHERE Type = 'IMPROVEMENT_CUSTOMS_HOUSE';
UPDATE Improvements SET NearbyFriendHeal = 5, ClearNegativePromotions = 1 WHERE Type = 'IMPROVEMENT_HOLY_SITE';

--BUILDING_SPECIALISTS
CREATE TABLE BuildingSpecialistTemp (BuildingType text, SpecialistType text,YieldType text);
INSERT INTO BuildingSpecialistTemp (BuildingType, SpecialistType,YieldType)
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV1','SPECIALIST_WRITER','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV1','SPECIALIST_ARTIST','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV1','SPECIALIST_MUSICIAN','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV2','SPECIALIST_WRITER','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV2','SPECIALIST_ARTIST','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV2','SPECIALIST_MUSICIAN','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV3','SPECIALIST_WRITER','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV3','SPECIALIST_ARTIST','YIELD_CULTURE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ARTISTIC_LV3','SPECIALIST_MUSICIAN','YIELD_CULTURE' UNION ALL

SELECT 'BUILDING_SPECIALISTS_SCIENTIFIC_LV1','SPECIALIST_SCIENTIST','YIELD_SCIENCE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_SCIENTIFIC_LV2','SPECIALIST_SCIENTIST','YIELD_SCIENCE' UNION ALL
SELECT 'BUILDING_SWEDEN_NOBEL_PRIZE','SPECIALIST_SCIENTIST','YIELD_SCIENCE' UNION ALL
SELECT 'BUILDING_SPECIALISTS_SCIENTIFIC_LV3','SPECIALIST_SCIENTIST','YIELD_SCIENCE' UNION ALL

SELECT 'BUILDING_SPECIALISTS_ENGINEERING_LV1','SPECIALIST_ENGINEER','YIELD_PRODUCTION' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ENGINEERING_LV2','SPECIALIST_ENGINEER','YIELD_PRODUCTION' UNION ALL
SELECT 'BUILDING_SPECIALISTS_ENGINEERING_LV3','SPECIALIST_ENGINEER','YIELD_PRODUCTION' UNION ALL

SELECT 'BUILDING_SPECIALISTS_MERCHANT_LV1','SPECIALIST_MERCHANT','YIELD_GOLD' UNION ALL
SELECT 'BUILDING_SPECIALISTS_MERCHANT_LV2','SPECIALIST_MERCHANT','YIELD_FOOD' UNION ALL
SELECT 'BUILDING_SPECIALISTS_MERCHANT_LV3','SPECIALIST_MERCHANT','YIELD_FOOD';

INSERT INTO Building_SpecialistYieldChanges(BuildingType,SpecialistType,YieldType,Yield)
SELECT BuildingType, SpecialistType, YieldType, 
(CASE WHEN YieldType = 'YIELD_FOOD'  THEN 1 ELSE 2 END)
FROM BuildingSpecialistTemp UNION ALL
SELECT BuildingType, SpecialistType, 'YIELD_GOLD', -2
FROM BuildingSpecialistTemp WHERE SpecialistType != 'SPECIALIST_MERCHANT';

DROP TABLE BuildingSpecialistTemp;

insert into Specialist_Resources (SpecialistType, ResourceType, Quantity, RequiredPolicyType, RequiredTechType) values 
('SPECIALIST_MERCHANT', 'RESOURCE_CONSUMER', 6, null, null),
('SPECIALIST_MERCHANT', 'RESOURCE_CONSUMER', 3, 'POLICY_MERCANTILISM', null),
('SPECIALIST_MERCHANT', 'RESOURCE_CONSUMER', 3, 'POLICY_SPACE_PROCUREMENTS', null),
('SPECIALIST_ENGINEER', 'RESOURCE_MANPOWER', 2, null, null),
('SPECIALIST_ENGINEER', 'RESOURCE_ELECTRICITY', 2, null, 'TECH_ELECTRICITY');
