insert into CorruptionLevels
(Type, IconString, ScoreLowerBoundBase, MapWidthModifier, MapHeightModifier, IsCapital, IsPuppet, CityHallBuildingClass, PublicSecurityBuildingClass) values
('CORRUPTION_PUPPET', '[ICON_PUPPET]', 0, 0, 0, 0, 1, 'BUILDINGCLASS_PUPPET_GOVERNEMENT', null),
('CORRUPTION_CAPITAL', '[ICON_CAPITAL]', 0, 0, 0, 1, 0, null, null),
('CORRUPTION_LV0', '', 0,  0, 0, 0, 0, null, null),
('CORRUPTION_LV1', '[ICON_CITYBANNER_CITY_LV1]', 1,  0, 0, 0, 0, 'BUILDINGCLASS_CITY_HALL_LV1', null),
('CORRUPTION_LV2', '[ICON_CITYBANNER_CITY_LV2]', 750,  0, 0, 0, 0, 'BUILDINGCLASS_CITY_HALL_LV2', 'BUILDINGCLASS_CONSTABLE'),
('CORRUPTION_LV3', '[ICON_CITYBANNER_CITY_LV3]', 1500, 100, 0, 0, 0, 'BUILDINGCLASS_CITY_HALL_LV3', 'BUILDINGCLASS_SHERIFF_OFFICE'),
('CORRUPTION_LV4', '[ICON_CITYBANNER_CITY_LV4]', 2700, 200, 0, 0, 0, 'BUILDINGCLASS_CITY_HALL_LV4', 'BUILDINGCLASS_POLICE_STATION'),
('CORRUPTION_LV5', '[ICON_CITYBANNER_CITY_LV5]', 3700, 200, 0, 0, 0, 'BUILDINGCLASS_CITY_HALL_LV5', 'BUILDINGCLASS_PROCURATORATE');

update Resources set CorruptionScoreChange = -99999 where CivilizationType = 'CIVILIZATION_INDONESIA';

insert into Policy_CorruptionLevelPolicyCostModifier (PolicyType, CorruptionLevelType, Modifier) values
('POLICY_REPRESENTATION', 'CORRUPTION_LV1', -5),
('POLICY_REPRESENTATION', 'CORRUPTION_LV2', -5),
('POLICY_REPRESENTATION', 'CORRUPTION_LV3', -5),
('POLICY_REPRESENTATION', 'CORRUPTION_LV4', -5),
('POLICY_REPRESENTATION', 'CORRUPTION_LV5', -5);
