ALTER TABLE UnitPromotions ADD IconStringSP text default '[ICON_PROMOTION_NEW_ATTRIBUTES]';

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_0]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_1]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_2]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_3]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_4]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_7]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_8]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_9]'        WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_11]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_12]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_13]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_14]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_15]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_16]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_19]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  19;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_22]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_24]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_25]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_26]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_27]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_28]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_29]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_40]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  40;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_41]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_42]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_43]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  43;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_44]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_45]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_46]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_47]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  47;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_49]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_50]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  50;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_51]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  51;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_52]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_54]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_61]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_62]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MAIN_ROBOT_PROMO_63]'       WHERE IconAtlas = 'MainRobotPromo_Atlas'  AND PortraitIndex =  63;

----------------------------------------- end-----------------------------------------------------

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_37]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_58]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_3]'           WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_4]'           WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_5]'           WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_6]'           WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_7]'           WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_8]'           WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_12]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_13]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 13;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_14]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_15]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_16]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 16;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_20]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_24]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_25]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 25;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_28]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_29]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_30]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 30;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_32]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_41]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_42]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_49]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_57]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_50]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_51]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_52]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_60]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_62]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VALERY_ATLAS_63]'          WHERE IconAtlas = 'VALERY_ATLAS'  AND PortraitIndex = 63;
----------------------------------------- end-----------------------------------------------------

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SMETAL]'                  WHERE IconAtlas = 'CIV_COLOR_ATLAS_FW_PROMOTI'  AND PortraitIndex = 2;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_00_6]'           WHERE IconAtlas = 'promoMUC_atlas_00'  AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_00_28]'          WHERE IconAtlas = 'promoMUC_atlas_00'  AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_00_37]'          WHERE IconAtlas = 'promoMUC_atlas_00'  AND PortraitIndex = 37;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_01_9]'           WHERE IconAtlas = 'promoMUC_atlas_01'  AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_01_2]'           WHERE IconAtlas = 'promoMUC_atlas_01'  AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_01_19]'          WHERE IconAtlas = 'promoMUC_atlas_01'  AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_01_20]'          WHERE IconAtlas = 'promoMUC_atlas_01'  AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_01_23]'          WHERE IconAtlas = 'promoMUC_atlas_01'  AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMOMUC_01_26]'          WHERE IconAtlas = 'promoMUC_atlas_01'  AND PortraitIndex = 26;
----------------------------------------- end-----------------------------------------------------
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS0]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS1]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS2]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS4]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS5]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS6]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS8]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS10]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS22]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORE_NEW_PROMOS_ATLAS23]'          WHERE IconAtlas = 'MORE_NEW_PROMOS_ATLAS'  AND PortraitIndex = 23;

----------------------------------------- VP0-----------------------------------------------------
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_4]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_5]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_6]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_7]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_9]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_11]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex =11 ;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_12]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_13]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex =13 ;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_14]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_16]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_17]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_18]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex =18 ;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_19]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_20]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_21]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_22]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_23]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_24]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_26]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_27]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_36]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_38]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_39]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_40]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_41]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_42]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_43]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_44]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_45]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_46]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_47]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_51]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_53]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_54]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_58]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_59]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_60]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_61]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_62]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP00_63]'          WHERE IconAtlas = 'promoVP_atlas_00'  AND PortraitIndex = 63;



----------------------------------------- VP1-----------------------------------------------------
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_3]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_5]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_7]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_10]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_11]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_12]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_13]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_14]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_15]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_16]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_17]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_18]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_20]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_21]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_22]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_28]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_29]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_30]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_47]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_55]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_56]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_58]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_59]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_61]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP01_62]'          WHERE IconAtlas = 'promoVP_atlas_01'  AND PortraitIndex = 62;


-----------------------------------------  VP2-----------------------------------------------------
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_0]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_1]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_2]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_3]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_4]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_5]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_6]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_7]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_8]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_9]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_10]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_12]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_15]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_17]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_20]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_21]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_23]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_26]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_31]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_41]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_56]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_57]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_58]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_61]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_62]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP02_63]'          WHERE IconAtlas = 'promoVP_atlas_02'  AND PortraitIndex = 63;

----------------------------------------- VP3--------------------------------------------
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_8]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_9]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_10]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_16]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_18]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_19]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_23]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_34]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_47]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_54]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_55]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_56]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VP03_59]'          WHERE IconAtlas = 'promoVP_atlas_03'  AND PortraitIndex = 59;

----------------------------------------- ROBOT PROMO--------------------------------------------
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ROBOT_PROMO_23]'          WHERE IconAtlas = 'robotPromo_Atlas'  AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ROBOT_PROMO_25]'          WHERE IconAtlas = 'robotPromo_Atlas'  AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ROBOT_PROMO_26]'          WHERE IconAtlas = 'robotPromo_Atlas'  AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ROBOT_PROMO_45]'          WHERE IconAtlas = 'robotPromo_Atlas'  AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ROBOT_PROMO_46]'          WHERE IconAtlas = 'robotPromo_Atlas'  AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ROBOT_PROMO_54]'          WHERE IconAtlas = 'robotPromo_Atlas'  AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_SPY_PROMOTION]'                     WHERE IconAtlas = 'SPY_PROMOTION_ATLAS'AND PortraitIndex = 0;  



----------------------------------------- end-----------------------------------------------------


UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ACCURACY_1]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ACCURACY_2]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ACCURACY_3]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AMBUSH_1]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AMBUSH_2]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AMPHIBIOUS]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BARRAGE_1]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BARRAGE_2]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BARRAGE_3]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BLITZ]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BOMBARDMENT_1]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BOMBARDMENT_2]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BOMBARDMENT_3]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HUNTDOWN_1]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COVER_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COVER_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DOGFIGHTING_1]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DOGFIGHTING_2]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DOGFIGHTING_3]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DRILL_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DRILL_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DRILL_3]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_EMBARKATION]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_EVASION]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FORMATION_1]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FORMATION_3]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FASTER_HEAL]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_INTERCEPTION_1]'      WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_INTERCEPTION_2]'      WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_INTERCEPTION_3]'      WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_LOGISTICS]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MARCH]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MEDIC]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MOBILITY]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_RANGE]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_INDIRECT_FIRE]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_REPAIR]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SCOUTING_1]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SCOUTING_2]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SCOUTING_3]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SIEGE_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SIEGE_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SIEGE_3]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SENTRY]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SHOCK_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SHOCK_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SHOCK_3]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SORTIE_1]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SUPPLY]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SURVIVALISM_1]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SURVIVALISM_2]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SURVIVALISM_3]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_TARGETING_1]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_TARGETING_2]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_TARGETING_3]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_VOLLEY]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_WOODSMAN]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_NEGATIVE_ATTRIBUTES]' WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ABILITY]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ATTRIBUTES]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BOARDING_PARTY_1]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BOARDING_PARTY_2]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BOARDING_PARTY_3]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COASTAL_RAIDER_1]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COASTAL_RAIDER_2]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COASTAL_RAIDER_3]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ALTITUDE_TRAINING]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DESERT_WARRIOR]'      WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_GOLDEN_AGE_POINTS]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_GOODY_HUT_PICKER]'    WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CHARGE_1]'            WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_LIGHTNING_WARFARE]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SAPPER]'              WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_EXTENDED_PARADROP]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_TRADE_MISSION_BONUS]' WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_BUFFALO_CHEST]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HOMELAND_GUARDIAN]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SELL_EXOTIC_GOODS]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ARMOR_PLATING_1]'     WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ARMOR_PLATING_2]'     WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ARMOR_PLATING_3]'     WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FLIGHT_DECK_1]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FLIGHT_DECK_2]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FLIGHT_DECK_3]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_WOLFPACK_1]'          WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_WOLFPACK_2]'          WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_WOLFPACK_3]'          WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AMBITION]'            WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ENEMY_BLADE]'         WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_EVIL_SPIRITS]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HEROISM]'             WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_INVULNERABIILITY]'    WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MYSTIC_BLADE]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_RECRUITMENT]'         WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_RESTLESSNESS]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SNEAK_ATTACK]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AMPHIBIOUS]'          WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SIEGE_3]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SHOCK_1]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_DRILL_1]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AMMUNITION_SUPPLY]'   WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_VOLLEY]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COMBAT_REDUCE]'       WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_PARADROP_PILLAGE]'    WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FREE_2]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_PARADROP_MOBILITY]'   WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FREE_1]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HOMELAND_GUARDIAN]'   WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_EMBARKATION]'         WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_LOGISTICS]'           WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_OUTFLANK]'            WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MEDIC]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MOBILITY]'            WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SIGEL]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SCOUTING_1]'          WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_GREEN]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HUGER]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SICKLES]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HOWARD]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MOBILITY_REDUCE]'     WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SIGHT_REDUCE]'        WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_EVASION_I]'           WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_EMP_ATTACK]'          WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COVER_3]'             WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SORTIE_2]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MISSILE_CARRIER]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CHARGE_NEW_1]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CHARGE_NEW_2]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CHARGE_NEW_3]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SUNDER_1]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SUNDER_2]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SUNDER_3]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HUNTDOWN_NEW_1]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HUNTDOWN_NEW_2]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HUNTDOWN_NEW_3]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CQB_COMBAT_1]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CQB_COMBAT_2]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_RANGE_REDUCE]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_PENETRATION]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COMBAT_REDUCE]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MORAL_WEAKEN]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MOVEMENT_LOST]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MOBILITY_REDUCE]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FIGHTER_SIEGE_1]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FIGHTER_SIEGE_2]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_LOSE_SUPPLY]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARRIER_SUPPLY_2]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARRIER_SUPPLY_3]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARGO_I]'             WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARGO_II]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARGO_IV]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARGO_VI]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARGO_IX]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ELITE]'               WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CAN_MOVE_AFTER]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_OUTFLANK]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_PARADROP]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FIRESUPPORT_1]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FIRESUPPORT_2]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COLLATERAL_DAMAGE_1]' WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CLUSTER_ROCKET_II]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_INFANTRY_COMBAT]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_GUNPOWDER_INFANTRY]'  WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ANTI_MOUNTED]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ANTI_TANK]'           WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ARCHERY_COMBAT]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CITY_SIEGE]'          WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SPLASH_DAMAGE]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SPECIAL_FORCES]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_MILITIA_COMBAT]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_KNIGHT_COMBAT]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_TANK_COMBAT]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HITANDRUN]'           WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HELI_ATTACK]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_NAVALMELEE_COMBAT]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_NAVAL_HIT_AND_RUN]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_NAVAL_CAPITAL_SHIP]'  WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SUBMARINE_COMBAT]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARRIER_UNIT]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ANTI_AIR_II]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AIR_ATTACK]'          WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_STRATEGIC_BOMBER]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CARRIER_FIGHTER]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_NAVAL_RANGED_SHIP]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ANTI_AIR_III]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 63;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_FORMATION_2]'         WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_AMBUSH_3]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COVER_3]'             WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SORTIE_2]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_RANGE]'               WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_REPAIR_II]'           WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SUNDER_1]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SUNDER_2]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[PROMOTION_CHARGE_1]'                     WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[PROMOTION_CHARGE_2]'                     WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[PROMOTION_CHARGE_3]'                     WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HUNTDOWN_2]'          WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_HUNTDOWN_3]'          WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COLLATERAL_DAMAGE_1]' WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COLLATERAL_DAMAGE_2]' WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_COLLATERAL_DAMAGE_3]' WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_RANGE_REDUCE]'        WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_CAN_MOVE_AFTER]'      WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_ELITE]'               WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_SPACE_ELEVATOR]'      WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_GROUP]'               WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEW_GROUP]'               WHERE IconAtlas = 'GROUP_PROMOTION_ATLAS';
