
--Traditional Policies: CapitalYieldChanges +4
INSERT INTO Policy_CapitalYieldChanges (PolicyType,YieldType,Yield)
SELECT 'POLICY_LANDED_ELITE','YIELD_FOOD',4 UNION ALL
SELECT 'POLICY_PREFECTURE','YIELD_CULTURE',4 UNION ALL
SELECT 'POLICY_OLIGARCHY','YIELD_PRODUCTION',4 ;

--POLICY_LANDED_ELITE
INSERT INTO Policy_ImprovementYieldChanges (PolicyType,ImprovementType,YieldType,Yield)
SELECT 'POLICY_LANDED_ELITE','IMPROVEMENT_TERRACE_FARM','YIELD_FOOD',1 UNION ALL
SELECT 'POLICY_LANDED_ELITE','IMPROVEMENT_POLDER','YIELD_FOOD',1 UNION ALL
SELECT 'POLICY_LANDED_ELITE','IMPROVEMENT_KASBAH','YIELD_FOOD',1 UNION ALL
SELECT 'POLICY_LANDED_ELITE','IMPROVEMENT_SHOSHONE_TIPI','YIELD_FOOD',1 ;

--POLICY_COASTAL_ADMINISTRATION
INSERT INTO Policy_BuildingClassYieldModifiers (PolicyType,BuildingClassType,YieldType,YieldMod)
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_SEAPORT','YIELD_SCIENCE',5 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_SHIPYARD','YIELD_SCIENCE',5 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_LIGHTHOUSE','YIELD_SCIENCE',3 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_HARBOR','YIELD_SCIENCE',3 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_WOOD_DOCK','YIELD_SCIENCE',3 UNION ALL

SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_SEAPORT','YIELD_PRODUCTION',5 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_SHIPYARD','YIELD_PRODUCTION',5 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_LIGHTHOUSE','YIELD_PRODUCTION',3 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_HARBOR','YIELD_PRODUCTION',3 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_WOOD_DOCK','YIELD_PRODUCTION',3 ;

INSERT INTO Policy_BuildingClassYieldChanges (PolicyType,BuildingClassType,YieldType,YieldChange)
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_SEAPORT','YIELD_GOLD',4 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_SHIPYARD','YIELD_GOLD',4 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_LIGHTHOUSE','YIELD_GOLD',4 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_HARBOR','YIELD_GOLD',4 UNION ALL
SELECT 'POLICY_COASTAL_ADMINISTRATION','BUILDINGCLASS_WOOD_DOCK','YIELD_GOLD',4 ;

--POLICY_BILL_OF_RIGHTS
INSERT INTO Policy_BuildingClassYieldChanges (PolicyType, BuildingClassType, YieldType, YieldChange)
SELECT 'POLICY_BILL_OF_RIGHTS', t1.BuildingClass, 
(CASE WHEN t1.SpecialistType='SPECIALIST_ENGINEER'  THEN 'YIELD_PRODUCTION' 
      WHEN t1.SpecialistType='SPECIALIST_SCIENTIST' THEN 'YIELD_SCIENCE' 
      WHEN t1.SpecialistType='SPECIALIST_MERCHANT'  THEN 'YIELD_GOLD'
      WHEN (t1.SpecialistType='SPECIALIST_WRITER' OR t1.SpecialistType='SPECIALIST_MUSICIAN' OR t1.SpecialistType='SPECIALIST_ARTIST') 
      THEN 'YIELD_CULTURE'
      end),
t1.SpecialistCount
FROM Buildings t1 LEFT JOIN BuildingClasses t2
ON t2.Type = t1.BuildingClass
WHERE t1.Type =  t2.DefaultBuilding AND t1.SpecialistCount > 0 
AND (t1.SpecialistType = 'SPECIALIST_ENGINEER' OR t1.SpecialistType='SPECIALIST_SCIENTIST' OR t1.SpecialistType='SPECIALIST_MERCHANT'
or t1.SpecialistType='SPECIALIST_WRITER' OR t1.SpecialistType='SPECIALIST_MUSICIAN' OR t1.SpecialistType='SPECIALIST_ARTIST');