ALTER TABLE UnitPromotions ADD IconStringSP text default '[ICON_PROMOTION_ATTRIBUTES]';
-- Group Promotions
INSERT OR REPLACE INTO IconTextureAtlases (Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn)
SELECT 'GROUP_PROMOTION_ATLAS'  ,32,    'PromotionsUnionSquare32_Exp2_CivilWar.dds',    5,5 UNION ALL
SELECT 'GROUP_PROMOTION_ATLAS'  ,45,    'Promotions45_Exp2_CivilWar.dds',               5,5 UNION ALL
SELECT 'GROUP_PROMOTION_ATLAS'  ,64,    'Promotions64_Exp2_CivilWar.dds',               5,5 UNION ALL
SELECT 'GROUP_PROMOTION_ATLAS'  ,256,   'PromotionsUnion256_Exp2_CivilWar.dds',         5,5;

INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP',               'TXT_KEY_PROMOTION_GROUP',             'TXT_KEY_PROMOTION_GROUP_HELP',             'AS2D_IF_LEVELUP',  0, 0, 0, 1, 0, 17, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP'            );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_AIR',           'TXT_KEY_PROMOTION_GROUP_AIR',         'TXT_KEY_PROMOTION_GROUP_HELP',             'AS2D_IF_LEVELUP',  0, 0, 0, 1, 0, 17, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_AIR'        );
--	INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE',          'TXT_KEY_PROMOTION_GROUP_MOVE',        'TXT_KEY_PROMOTION_GROUP_MOVE_HELP',        'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE'       );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_I',        'TXT_KEY_PROMOTION_GROUP_MOVE_I',      'TXT_KEY_PROMOTION_GROUP_MOVE_I_HELP',      'AS2D_IF_LEVELUP', -1, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_I'     );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_II',       'TXT_KEY_PROMOTION_GROUP_MOVE_II',     'TXT_KEY_PROMOTION_GROUP_MOVE_II_HELP',     'AS2D_IF_LEVELUP', -2, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_II'    );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_III',      'TXT_KEY_PROMOTION_GROUP_MOVE_III',    'TXT_KEY_PROMOTION_GROUP_MOVE_III_HELP',    'AS2D_IF_LEVELUP', -3, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_III'   );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_IV',       'TXT_KEY_PROMOTION_GROUP_MOVE_IV',     'TXT_KEY_PROMOTION_GROUP_MOVE_IV_HELP',     'AS2D_IF_LEVELUP', -4, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_IV'    );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_V',        'TXT_KEY_PROMOTION_GROUP_MOVE_V',      'TXT_KEY_PROMOTION_GROUP_MOVE_V_HELP',      'AS2D_IF_LEVELUP', -5, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_V'     );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X',        'TXT_KEY_PROMOTION_GROUP_MOVE_X',      'TXT_KEY_PROMOTION_GROUP_MOVE_X_HELP',      'AS2D_IF_LEVELUP',  0, 0, 0, 1, 1, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X'     );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_I',      'TXT_KEY_PROMOTION_GROUP_MOVE_X_I',    'TXT_KEY_PROMOTION_GROUP_MOVE_X_I_HELP',    'AS2D_IF_LEVELUP',  0, 0, 0, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_I'   );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_II',     'TXT_KEY_PROMOTION_GROUP_MOVE_X_II',   'TXT_KEY_PROMOTION_GROUP_MOVE_X_II_HELP',   'AS2D_IF_LEVELUP',  0, 0, 0, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_II'  );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_III',    'TXT_KEY_PROMOTION_GROUP_MOVE_X_III',  'TXT_KEY_PROMOTION_GROUP_MOVE_X_III_HELP',  'AS2D_IF_LEVELUP',  0, 0, 0, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_III' );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_IV',     'TXT_KEY_PROMOTION_GROUP_MOVE_X_IV',   'TXT_KEY_PROMOTION_GROUP_MOVE_X_IV_HELP',   'AS2D_IF_LEVELUP',  0, 0, 0, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_IV'  );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_V',      'TXT_KEY_PROMOTION_GROUP_MOVE_X_V',    'TXT_KEY_PROMOTION_GROUP_MOVE_X_V_HELP',    'AS2D_IF_LEVELUP',  0, 0, 0, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_V'   );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_VI',     'TXT_KEY_PROMOTION_GROUP_MOVE_X_VI',   'TXT_KEY_PROMOTION_GROUP_MOVE_X_VI_HELP',   'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_VI'  );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_VII',    'TXT_KEY_PROMOTION_GROUP_MOVE_X_VII',  'TXT_KEY_PROMOTION_GROUP_MOVE_X_VII_HELP',  'AS2D_IF_LEVELUP',  1, 0, 0, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_VII' );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_VII_FS', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_VII',  'TXT_KEY_PROMOTION_GROUP_MOVE_X_VII_HELP',  'AS2D_IF_LEVELUP',  1, 0, 0, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_VII' );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_VIII',   'TXT_KEY_PROMOTION_GROUP_MOVE_X_VIII', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_VIII_HELP', 'AS2D_IF_LEVELUP',  0, 1, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_VIII');
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_IX',     'TXT_KEY_PROMOTION_GROUP_MOVE_X_IX',   'TXT_KEY_PROMOTION_GROUP_MOVE_X_IX_HELP',   'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_IX'  );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_MOVE_X_X',      'TXT_KEY_PROMOTION_GROUP_MOVE_X_X',    'TXT_KEY_PROMOTION_GROUP_MOVE_X_X_HELP',    'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_MOVE_X_X'   );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_MOVELIFT_I',          'TXT_KEY_PROMOTION_MOVELIFT_I',        'TXT_KEY_PROMOTION_MOVELIFT_I_HELP',        'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_MOVELIFT_I'       );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_MOVELIFT_II',         'TXT_KEY_PROMOTION_MOVELIFT_II',       'TXT_KEY_PROMOTION_MOVELIFT_II_HELP',       'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_MOVELIFT_II'      );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_MOVELIFT_III',        'TXT_KEY_PROMOTION_MOVELIFT_III',      'TXT_KEY_PROMOTION_MOVELIFT_III_HELP',      'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_MOVELIFT_III'     );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_MOVELIFT_IV',         'TXT_KEY_PROMOTION_MOVELIFT_IV',       'TXT_KEY_PROMOTION_MOVELIFT_IV_HELP',       'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_MOVELIFT_IV'      );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_MOVELIFT_V',          'TXT_KEY_PROMOTION_MOVELIFT_V',        'TXT_KEY_PROMOTION_MOVELIFT_V_HELP',        'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 23, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_MOVELIFT_V'       );
INSERT OR REPLACE INTO UnitPromotions (Type, Description, Help, Sound, MovesChange, RoughTerrainEndsTurn, LostWithUpgrade, CannotBeChosen, OnlyDefensive, PortraitIndex, IconAtlas, PediaType, PediaEntry) VALUES ('PROMOTION_GROUP_BUILD',         'TXT_KEY_PROMOTION_GROUP_BUILD',       'TXT_KEY_PROMOTION_GROUP_BUILD_HELP',       'AS2D_IF_LEVELUP',  0, 0, 1, 1, 0, 17, 'GROUP_PROMOTION_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_GROUP_BUILD'      );
INSERT OR REPLACE INTO UnitPromotions_Terrains (PromotionType, TerrainType, Attack, Defense, Impassable, PassableTech) VALUES ('PROMOTION_GROUP_MOVE_X_II', 'TERRAIN_HILL',   10, 10, 0, NULL);
INSERT OR REPLACE INTO UnitPromotions_Terrains (PromotionType, TerrainType, Attack, Defense, Impassable, PassableTech) VALUES ('PROMOTION_GROUP_MOVE_X_V',  'TERRAIN_SNOW',   25, 25, 0, NULL);
INSERT OR REPLACE INTO UnitPromotions_Terrains (PromotionType, TerrainType, Attack, Defense, Impassable, PassableTech) VALUES ('PROMOTION_GROUP_MOVE_X_V',  'TERRAIN_TUNDRA', 25, 25, 0, NULL);
INSERT OR REPLACE INTO UnitPromotions_Terrains (PromotionType, TerrainType, Attack, Defense, Impassable, PassableTech) VALUES ('PROMOTION_GROUP_MOVE_X_V',  'TERRAIN_HILL',   25, 25, 0, NULL);
INSERT OR REPLACE INTO UnitPromotions_Terrains (PromotionType, TerrainType, Attack, Defense, Impassable, PassableTech) VALUES ('PROMOTION_GROUP_MOVE_X_IX', 'TERRAIN_OCEAN',   0,  0, 1, NULL);
INSERT OR REPLACE INTO UnitPromotions_Terrains (PromotionType, TerrainType, Attack, Defense, Impassable, PassableTech) VALUES ('PROMOTION_GROUP_MOVE_X_X',  'TERRAIN_OCEAN',   0,  0, 1, 'TECH_ASTRONOMY');
	
-- UnitPromotions - SET IconStringSP
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ACCURACY_1]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ACCURACY_2]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ACCURACY_3]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AMBUSH_1]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AMBUSH_2]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AMPHIBIOUS]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BARRAGE_1]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BARRAGE_2]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BARRAGE_3]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BLITZ]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BOMBARDMENT_1]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BOMBARDMENT_2]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BOMBARDMENT_3]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HUNTDOWN_1]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COVER_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COVER_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DOGFIGHTING_1]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DOGFIGHTING_2]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DOGFIGHTING_3]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DRILL_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DRILL_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DRILL_3]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EMBARKATION]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EVASION]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FORMATION_1]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FORMATION_3]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FASTER_HEAL]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_INTERCEPTION_1]'      WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_INTERCEPTION_2]'      WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_INTERCEPTION_3]'      WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_LOGISTICS]'           WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MARCH]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MEDIC]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MOBILITY]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_RANGE]'               WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_INDIRECT_FIRE]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_REPAIR]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SCOUTING_1]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SCOUTING_2]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SCOUTING_3]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SIEGE_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SIEGE_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SIEGE_3]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SENTRY]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SHOCK_1]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SHOCK_2]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SHOCK_3]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SORTIE_1]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SUPPLY]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SURVIVALISM_1]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SURVIVALISM_2]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SURVIVALISM_3]'       WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TARGETING_1]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TARGETING_2]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TARGETING_3]'         WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VOLLEY]'              WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_WOODSMAN]'            WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEGATIVE_ATTRIBUTES]' WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ABILITY]'             WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ATTRIBUTES]'          WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BOARDING_PARTY_1]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BOARDING_PARTY_2]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BOARDING_PARTY_3]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COASTAL_RAIDER_1]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COASTAL_RAIDER_2]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COASTAL_RAIDER_3]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS' AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ALTITUDE_TRAINING]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DESERT_WARRIOR]'      WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_GOLDEN_AGE_POINTS]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_GOODY_HUT_PICKER]'    WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CHARGE_1]'            WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_LIGHTNING_WARFARE]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SAPPER]'              WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTENDED_PARADROP]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TRADE_MISSION_BONUS]' WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_BUFFALO_CHEST]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HOMELAND_GUARDIAN]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SELL_EXOTIC_GOODS]'   WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ARMOR_PLATING_1]'     WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ARMOR_PLATING_2]'     WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ARMOR_PLATING_3]'     WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FLIGHT_DECK_1]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FLIGHT_DECK_2]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FLIGHT_DECK_3]'       WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_WOLFPACK_1]'          WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_WOLFPACK_2]'          WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_WOLFPACK_3]'          WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AMBITION]'            WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ENEMY_BLADE]'         WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EVIL_SPIRITS]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HEROISM]'             WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_INVULNERABIILITY]'    WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MYSTIC_BLADE]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_RECRUITMENT]'         WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_RESTLESSNESS]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SNEAK_ATTACK]'        WHERE IconAtlas = 'KRIS_SWORDSMAN_PROMOTION_ATLAS' AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AMPHIBIOUS]'          WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SIEGE_3]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SHOCK_1]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_DRILL_1]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AMMUNITION_SUPPLY]'   WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_VOLLEY]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COMBAT_REDUCE]'       WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PARADROP_PILLAGE]'    WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FREE_2]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PARADROP_MOBILITY]'   WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FREE_1]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HOMELAND_GUARDIAN]'   WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EMBARKATION]'         WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_LOGISTICS]'           WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_OUTFLANK]'            WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MEDIC]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MOBILITY]'            WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SIGEL]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SCOUTING_1]'          WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_GREEN]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HUGER]'               WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SICKLES]'             WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HOWARD]'              WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MOBILITY_REDUCE]'     WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SIGHT_REDUCE]'        WHERE (IconAtlas = 'CIVIL_WAR_UNION_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_CONFED_PROMOTION_ATLAS' OR IconAtlas = 'CIVIL_WAR_PROMOTION_ATLAS') AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EVASION_I]'           WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EMP_ATTACK]'          WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COVER_3]'             WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SORTIE_2]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MISSILE_CARRIER]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CHARGE_NEW_1]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CHARGE_NEW_2]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CHARGE_NEW_3]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SUNDER_1]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SUNDER_2]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SUNDER_3]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HUNTDOWN_NEW_1]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HUNTDOWN_NEW_2]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HUNTDOWN_NEW_3]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CQB_COMBAT_1]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CQB_COMBAT_2]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_RANGE_REDUCE]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PENETRATION]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COMBAT_REDUCE]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MORAL_WEAKEN]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MOVEMENT_LOST]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MOBILITY_REDUCE]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FIGHTER_SIEGE_1]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FIGHTER_SIEGE_2]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_LOSE_SUPPLY]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARRIER_SUPPLY_2]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARRIER_SUPPLY_3]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARGO_I]'             WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARGO_II]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARGO_IV]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARGO_VI]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARGO_IX]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ELITE]'               WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CAN_MOVE_AFTER]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_OUTFLANK]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PARADROP]'            WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FIRESUPPORT_1]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FIRESUPPORT_2]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COLLATERAL_DAMAGE_1]' WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CLUSTER_ROCKET_II]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_INFANTRY_COMBAT]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_GUNPOWDER_INFANTRY]'  WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ANTI_MOUNTED]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ANTI_TANK]'           WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ARCHERY_COMBAT]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CITY_SIEGE]'          WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SPLASH_DAMAGE]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SPECIAL_FORCES]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_MILITIA_COMBAT]'      WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_KNIGHT_COMBAT]'       WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TANK_COMBAT]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HITANDRUN]'           WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HELI_ATTACK]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NAVALMELEE_COMBAT]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NAVAL_HIT_AND_RUN]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NAVAL_CAPITAL_SHIP]'  WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SUBMARINE_COMBAT]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARRIER_UNIT]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ANTI_AIR_II]'         WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AIR_ATTACK]'          WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_STRATEGIC_BOMBER]'    WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CARRIER_FIGHTER]'     WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NAVAL_RANGED_SHIP]'   WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ANTI_AIR_III]'        WHERE IconAtlas = 'SP_PROMOTION_ATLAS' AND PortraitIndex = 63;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FORMATION_2]'         WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_AMBUSH_3]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COVER_3]'             WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SORTIE_2]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_RANGE]'               WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_REPAIR_II]'           WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SUNDER_1]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SUNDER_2]'            WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  7;
UPDATE UnitPromotions SET IconStringSP = '[PROMOTION_CHARGE_1]'                 WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  8;
UPDATE UnitPromotions SET IconStringSP = '[PROMOTION_CHARGE_2]'                 WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex =  9;
UPDATE UnitPromotions SET IconStringSP = '[PROMOTION_CHARGE_3]'                 WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HUNTDOWN_2]'          WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_HUNTDOWN_3]'          WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COLLATERAL_DAMAGE_1]' WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COLLATERAL_DAMAGE_2]' WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COLLATERAL_DAMAGE_3]' WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_RANGE_REDUCE]'        WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CAN_MOVE_AFTER]'      WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_ELITE]'               WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SPACE_ELEVATOR]'      WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_GROUP]'               WHERE (IconAtlas = 'SP_PROMOTION_OLD_ATLAS' OR IconAtlas = 'SPPROMOTION_ATLAS') AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_GROUP]'               WHERE IconAtlas = 'GROUP_PROMOTION_ATLAS';


INSERT OR REPLACE INTO IconFontTextures(IconFontTexture,IconFontTextureFile)
SELECT 'ICON_FONT_TEXTURE_SP10_PROMOTIONS','FontIcons_Promotions_SP10';

INSERT OR REPLACE INTO IconFontMapping(IconName,IconFontTexture,IconMapping) 
SELECT 'ICON_PROMOTION_SP10_' || CAST(PortraitIndex+1 AS TEXT),'ICON_FONT_TEXTURE_SP10_PROMOTIONS',PortraitIndex+1 
FROM UnitPromotions WHERE IconAtlas = 'SP10_PROMOTION_ATLAS';

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_SP10_' || CAST(PortraitIndex+1 AS TEXT)|| ']'
WHERE IconAtlas = 'SP10_PROMOTION_ATLAS';