insert into Unit_FreePromotions (UnitType, PromotionType)
select `Type`, 'PROMOTION_ANTI_RIOT_BONUS'
from Units 
where Class = 'UNITCLASS_MARINE' or Class = 'UNITCLASS_PARATROOPER' or Class = 'UNITCLASS_XCOM_SQUAD';

INSERT INTO UnitPromotions_PromotionUpgrade(PromotionType, JudgePromotionType, NewPromotionType)
SELECT 'PROMOTION_FORMATION_1', 'PROMOTION_ANTI_TANK', 'PROMOTION_AMBUSH_1' UNION ALL
SELECT 'PROMOTION_FORMATION_2', 'PROMOTION_ANTI_TANK', 'PROMOTION_AMBUSH_2';

CREATE TABLE IF NOT EXISTS SPCarrierTransferPromotions(CarrierPromotionType TEXT PRIMARY KEY REFERENCES UnitPromotions(Type), FighterPromotionType TEXT REFERENCES UnitPromotions(Type));
INSERT INTO SPCarrierTransferPromotions
        (CarrierPromotionType,                      FighterPromotionType)
VALUES	('PROMOTION_CARRIER_FIGHTER_ANTI_AIR_1',    'PROMOTION_CARRIER_FIGHTER_AIRFIGHT_1'),
        ('PROMOTION_CARRIER_FIGHTER_ANTI_AIR_2',    'PROMOTION_CARRIER_FIGHTER_AIRFIGHT_2'),
        ('PROMOTION_CARRIER_FIGHTER_ATTACK_1',      'PROMOTION_CARRIER_FIGHTER_ATTACK_1'),
        ('PROMOTION_CARRIER_FIGHTER_ATTACK_2',      'PROMOTION_CARRIER_FIGHTER_ATTACK_2'),
        ('PROMOTION_CARRIER_FIGHTER_SIEGE_1',       'PROMOTION_CARRIER_FIGHTER_SIEGE_1'),
        ('PROMOTION_CARRIER_FIGHTER_SIEGE_2',       'PROMOTION_CARRIER_FIGHTER_SIEGE_2'),
        ('PROMOTION_CARRIER_SUPPLY_2',              'PROMOTION_CARRIER_SUPPLY_2'),
        ('PROMOTION_CARRIER_FIGHTER_SORTIE',        'PROMOTION_CARRIER_FIGHTER_SORTIE'),
        ('PROMOTION_GAIN_EXPERIENCE',               'PROMOTION_GAIN_EXPERIENCE');